[package]
name = "tibs"
version = "0.1.0"
edition = "2024"

[dependencies]
glutin = "0.32.2"
raw-window-handle = "0.6.2"
drm = "0.14.1"
gbm = "0.18.0"
glfw = { version = "0.59.0", optional = true }
color-eyre = "0.6.3"
[build-dependencies]
gl_generator = "0"

[features]
glfw = ["dep:glfw"]
